package com.example.a10616.testdemo.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a10616.testdemo.database.bean.Teacher;

import com.example.a10616.testdemo.database.dao.TeacherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teacherDaoConfig;

    private final TeacherDao teacherDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        teacherDao = new TeacherDao(teacherDaoConfig, this);

        registerDao(Teacher.class, teacherDao);
    }
    
    public void clear() {
        teacherDaoConfig.clearIdentityScope();
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

}
